env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - react-hooks
  - babel
  - jest
globals:
  module: true
  require: true
  CONFIG: true
rules:
  indent:
    - error
    - tab
    - {
      SwitchCase: 1
    }
  quotes:
    - off
    - double
  semi:
    - off
  babel/semi:
    - error
    - always
    - {
      omitLastInOneLineBlock: true
    }
  getter-return:
    - error
    - {
      allowImplicit: true
    }
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
